
name: Selenium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    # Using specific Chrome version
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: '131.0.6778.205'
        
    - name: Get Chrome version
      run: |
        google-chrome --version
        echo "CHROME_VERSION=$(google-chrome --version | awk '{print $3}')" >> $GITHUB_ENV
        
    # Setup matching ChromeDriver version
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        # Using the major version number from Chrome
        chromedriver-version: '131.0'
      
    - name: Start ChromeDriver and Xvfb
      run: |
        sudo apt-get install -y xvfb
        Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        export DISPLAY=:99
        chromedriver --version
        chromedriver --url-base=/wd/hub &
        sleep 5
        
    - name: Run Tests
      run: mvn clean test
      env:
        DISPLAY: :99
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/
        
    - name: Generate Test Report
      if: always()
      run: mvn surefire-report:report-only
      
    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: target/site/
