
name: Selenium CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
        
    - name: Setup Chrome
      run: browser-actions/setup-chrome@latest

    - name: SetupChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Start ChromeDriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

    - name: Run Tests
      run: mvn clean test

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with: 
        name: test-results
        path: target/surefire-reports

    - name: Generate Test Report
      if: always()
      run: mvn surefire-report:report-only
      
    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: target/site/
